name: igsc2021
channels:
  - conda-forge
dependencies:
  - ca-certificates=2024.12.14
  - certifi=2024.12.14
  - ipykernel=6.29.5
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - notebook=7.3.2
  - numpy=1.26.4
  - openssl=3.4.0
  - pandas=2.2.3
  - pip=24.3.1
  - python=3.12.8
  - scikit-image=0.25.0
  - scipy=1.15.0
  - tensorflow=2.17.0
  - pip:
      - opencv-python==4.10.0.84
